### ISSUE TITLE
Compile error during install: "fatal error: libudev.h: No such file or directory"

### ISSUE THREAD

**Issue by andrewjbates** [asednev/homebridge-plugin-govee#6]
**Describe Your Problem:**
- Plugin installs but with error messages
- Plugin does not create any log entries after restart
- No devices supported by this plugin are found

**Logs:**
_Install:_
```
/homebridge # npm install --save homebridge-plugin-govee@latest

> usb@1.6.3 install /homebridge/node_modules/homebridge-plugin-govee/node_modules/usb
> prebuild-install --verbose || node-gyp rebuild

prebuild-install info begin Prebuild-install version 5.3.6
prebuild-install info looking for cached prebuild @ /root/.npm/_prebuilds/a5f1ee-usb-v1.6.3-node-v83-linuxmusl-x64.tar.gz
prebuild-install http request GET https://github.com/tessel/node-usb/releases/download/v1.6.3/usb-v1.6.3-node-v83-linuxmusl-x64.tar.gz
prebuild-install http 404 https://github.com/tessel/node-usb/releases/download/v1.6.3/usb-v1.6.3-node-v83-linuxmusl-x64.tar.gz
prebuild-install WARN install No prebuilt binaries found (target=14.15.0 runtime=node arch=x64 libc=musl platform=linux)
make: Entering directory '/homebridge/node_modules/homebridge-plugin-govee/node_modules/usb/build'
  CC(target) Release/obj.target/libusb/libusb/libusb/core.o
  CC(target) Release/obj.target/libusb/libusb/libusb/descriptor.o
  CC(target) Release/obj.target/libusb/libusb/libusb/hotplug.o
  CC(target) Release/obj.target/libusb/libusb/libusb/io.o
  CC(target) Release/obj.target/libusb/libusb/libusb/strerror.o
  CC(target) Release/obj.target/libusb/libusb/libusb/sync.o
  CC(target) Release/obj.target/libusb/libusb/libusb/os/poll_posix.o
  CC(target) Release/obj.target/libusb/libusb/libusb/os/threads_posix.o
  CC(target) Release/obj.target/libusb/libusb/libusb/os/linux_usbfs.o
  CC(target) Release/obj.target/libusb/libusb/libusb/os/linux_udev.o
../libusb/libusb/os/linux_udev.c:40:10: fatal error: libudev.h: No such file or directory
   40 | #include <libudev.h>
      |          ^~~~~~~~~~~
compilation terminated.
make: *** [libusb.target.mk:150: Release/obj.target/libusb/libusb/libusb/os/linux_udev.o] Error 1
make: Leaving directory '/homebridge/node_modules/homebridge-plugin-govee/node_modules/usb/build'
gyp ERR! build error
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:194:23)
gyp ERR! stack     at ChildProcess.emit (events.js:315:20)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:277:12)
gyp ERR! System Linux 5.4.0-52-generic
gyp ERR! command "/usr/local/bin/node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /homebridge/node_modules/homebridge-plugin-govee/node_modules/usb
gyp ERR! node -v v14.15.0
gyp ERR! node-gyp -v v5.1.0
gyp ERR! not ok
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: usb@1.6.3 (node_modules/homebridge-plugin-govee/node_modules/usb):
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: usb@1.6.3 install: `prebuild-install --verbose || node-gyp rebuild`
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: Exit status 1

+ homebridge-plugin-govee@1.0.3
updated 1 package in 19.522s
```

_Startup:_
```
Loaded plugin: homebridge-plugin-govee@1.0.3
Registering platform 'homebridge-plugin-govee.GoveeHomebridgePlugin'
```

**Plugin Config:**

```json
{
    "bridge": {
...
    },
    "accessories": [],
    "platforms": [
        {
...
            "platform": "config"
        },
        {
...
            "platform": "BelkinWeMo"
        },
        {
...
            "platform": "myQ"
        },
        {
...
            "platform": "HarmonyHubWebSocket"
        },
        {
...
            "platform": "Camera-ffmpeg"
        },
        {
...
            "platform": "TplinkSmarthome"
        },
        {
            "name": "Govee",
            "batteryThreshold": 25,
            "debug": true,
            "platform": "GoveeHomebridgePlugin"
        }
    ]
}
```

**Screenshots:**
n/a

**Environment:**

* **Plugin Version**: 1.0.3
* **Homebridge Version**: 1.1.6
* **Node.js Version**: v14.15.0
* **NPM Version**: 6.14.8
* **Operating System**: Docker

**Comment by andrewjbates** [comment]
**Resolved.**

This was fundamentally an issue with the Docker container being underprovisioned for this plugin.

To resolve, you must install a bluetooth-related package (eudev) and run a command (setcap) to allow `noble` to run under the Docker user.

Original `docker-compose.yml`:
```
...
  homebridge:
    image: oznu/homebridge:latest
    container_name: homebridge
    restart: unless-stopped
    network_mode: host
    environment:
      - TZ=US/Eastern
      - PGID=1000
      - PUID=1000
      - HOMEBRIDGE_CONFIG_UI=1
      - HOMEBRIDGE_CONFIG_UI_PORT=8080
    volumes:
      - './homebridge/data:/homebridge'
...
```

Revised `docker-compose.yml`:
```
...
  homebridge:
    build: ./homebridge
    container_name: homebridge
    restart: unless-stopped
    network_mode: host
    environment:
      - TZ=US/Eastern
      - PGID=1000
      - PUID=1000
      - HOMEBRIDGE_CONFIG_UI=1
      - HOMEBRIDGE_CONFIG_UI_PORT=8080
    volumes:
      - './homebridge/data:/homebridge'
    privileged: true
    devices:
     - '/dev:/dev'
...
```

The new `Dockerfile` (located in `./homebridge/` relative to `docker-compose.yml`):
```
FROM oznu/homebridge:latest

RUN apk add eudev-dev
RUN setcap cap_net_raw+eip $(eval readlink -f `which node`)
```
